### PR TITLE
Install-script (mysql only)

### PR DESCRIPTION
**Pull request by schnoog**
Implementation of a basic install script.
If support dba is missing or no db connection possible, redirect to install.php
DB credentials entered in install.php will be stored if verification was successful
Credential form uses default values not dba.php readout.

### CODE REVIEW

**Comment by schnoog** [comment]
Contains a very basic DB versioning script. 
Installation will iterate through the dbm_*.php files in support/database_migration therefore also suitable for updates.
Simple add a dbm_002.php for the next revision

**Comment by jrie** [comment]
I receive the error 500 from Apache when install.php is called. I used a fresh checkout from your repository for testing.

**Comment by jrie** [comment]
I receive the error 500 on fresh checkout.

This is in reason of missing permissions for the Smartyfolders:
```
sudo chown -R www-data smartyfolders/
sudo chgrp -R www-data smartyfolders/
```
Would be nice if the script would also check if smartyfolders is write and or readable.

**Comment by schnoog** [comment]
No problem, simply reject the PR and I'll implement it

**Comment by jrie** [comment]
Closed for rework.

**Pull request closed without merging**
