### PR TITLE
Install-Script

### PR DESCRIPTION
**Pull request by schnoog**
Implementation of a basic install script.
If support dba is missing or no db connection possible, redirect to install.php
DB credentials entered in install.php will be stored if verification was successful
Credential form uses default values not dba.php read out.
Checks for write access of required folders..

### CODE REVIEW

**Comment by jrie** [comment]
When there is no database present, but a user with basic rights on the database, I receive the following error: `Datenbank-Verbindung nicht möglich. Bitte kontrolliere die Zugangsdaten`
can you check on this. I used the default input values, so "tlvUser" as username and password which should match.

Also, if `dba.php` is created and the username and password are changed inside the installation form, the file is not updated accordingly and stays with previous inputs.

**Comment by schnoog** [comment]
Database creation is not (yet) implemented, only access to an existing database.
(similar to the old setup procedure where also an existing database is required)
If you prefer it, I can implement that it will be created later today.

The data in dba.php is only changed if the connection was successful.

**Comment by jrie** [comment]
Two points:
1) Can you implement the language selection from within the installer page
2) Some styling should be done on initial errors when `smartyfolders` and `languages` are not write or readable.

Other then that the solution is looking good! :+1:

**Comment by schnoog** [comment]
Main problem: Without write permissions there's no way to use the template system. 
Therefore I had to add this JS into install.php

ul.nav is declared empty twice (in the main nav.tpl it's filled with <li> elements)

**Comment by schnoog** [comment]
Will re-submit the PR after changes are applied.

**Pull request closed without merging**
